version: '3.8'

services:
  exchron-backend:
    build: .
    container_name: exchron-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    # volumes:
      # Uncomment if you want to persist logs
      # - ./logs:/app/logs
      # Uncomment if you want to mount data externally
      # - ./data:/app/data:ro
      # - ./models:/app/models:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 4G
    #     reservations:
    #       cpus: '1.0'
    #       memory: 2G